# ~/.config/tmux/tmux.conf

# General Settings
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 100000
set -g automatic-rename off
set -s exit-empty off
set -s escape-time 0

# Prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message " [!] Configuration reloaded"

# Status Bar
set -g status-style "fg=#ffffff #{?client_prefix,reverse,bg=green}"
set -g status-right "#S [%H:%M]"
set -g status-left  ""
set -g window-status-format "[#I] #W"
set -g window-status-current-format "#[underscore][#I] #W"
set -g window-status-separator "  "

# Copy Mode
set -g mode-keys vi
set -g set-clipboard external
